services:
  postgres-db:
    container_name: todo
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: todo_dev
      POSTGRES_PASSWORD: todo_dev12
      POSTGRES_DB: todo
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5435:5432"

volumes:
  postgresql_data:
    driver: local
